print('=============================================')
print('')
print('Bem vindo ao céu, você irá para um julgamento. \nVamos verificar suas respostas e decidir seu destino.')
resp1 = input('Você está vivo ou morto? ')
print(resp1.isalpha())
print('')
resp2 = input('Você gosta de viver? E quantos anos você tem agora? ')
print(resp2.isalnum())
print('')
resp3 = input('Escreva a palavra que você mais fala: ')
print('O tipo primitivo é: '), print(type(resp3))
print('')
print('É uma palavra somente com letras? ', resp3.isalpha())
print('É uma palavra somente com números? ', resp3.isnumeric())
print('É uma palavra com letras e/ou números? ', resp3.isalnum())
print('É uma palavra somente em maiusculo? ', resp3.isupper()) 
print('É uma palavra somente em mínusculo? ', resp3.islower())
print('Esta palavra está Capitalizada? ', resp3.istitle())

print('')
print('=============================================')