print('----------------------------')
print('Exercício 2 - Aniversário + 10 Anos!')
print('')
idade1 = input('Vamos, me diga, qual é a sua idade!\n')
print('')
print('Interessante! Mas quero saber mais!')
dianas1 = input('Quando, como... Melhor, Que dia você nasceu?!\n')
print('')
print('Mais.. MAIS!')
mes1 = input('Qual é o seu mês de nascimento???\n')
print('')
print('Maravilhoso... E por ultimo..')
ano1 = input('Em que ano você nasceu?!\n')
print('')
print('Entendo, então seu aniversário é no dia', dianas1 + '/' + mes1 + '/' + ano1 + '.') 
print('')
print('Isso significa que daqui 10 anos, você irá ter', int(idade1) + 10, 'anos de idade!')
print('Portanto você deverá estar vivo até', int(ano1) + 10, '\nNesse caso, nos veremos até lá!') 
print('')
print('----------------------------')