print('-'*24)
print('')
print('====================')
print('Conversor de Moedas')
print('====================')
print('Cotação Atual: US$1.00 = R$4.78')
print('')
print('='*15)
resp = (input('Você pode escolher qual tipo de conversão quer fazer: \nCaso queira de Real para Dolar, escreva [Dolar]; \nCaso queira de Dolar para Real, escreva [Real]; \nEscreva aqui: '))
print('='*15)
print('')
if (resp == 'Dolar'):
    real = (float(input('Digite o valor em reais (R$), para a conversão: ')))
    print(f'A partir da cotação atual, com R${real:.2f} você poderia comprar US${real/4.78:.2f}.')
else:
    Dolar = (float(input('Digite o valor em Dolar (US$), para a conversão em reais: ')))
    print(f'A partir da cotação atual, com US${Dolar:.2f}, você poderia comprar R${Dolar*4.78:.2f}')
print('')
print('-'*24)