print('-'*24)
print('')
print('====================')
print('AutomaticEXDescontos')
print('====================')
print('')
print('-'*15)
print('Para usar o descontador automático de preços, siga as instruções: \nVocê deverá informar o preço do produto, e a porcentagem da qual será descontada. ')
price = (float(input('Informe o preço do produto: RS$')))
desc = (int(input('Informe a porcentagem de desconto que deverá ser aplicada. [Informe somente o número]: ')))
resul = price*desc/100
print('-'*15)
print('')
print(f'O produto que antes custava RS${price:.2f}, com um desconto de {desc}%, agora vai custar: RS${price-resul:.2f}')
print(f'Do preço original, RS${resul:.2f} foram descontados.')
print('')
print(''*24)