print('----------------------------')
print('Desafio 1 - Olá!')
print('')
nome1 = input('Me diga seu nome! Imediatamente:\n')
print('')
print('Seja muito bem vindo, Lorde', nome1 + '. \nEspero que goste de sua nova casa.')
print('')
print('----------------------------')