print('-'*24)
print('')

print('==================')
print('UltraPaintingArea')
print('==================')
print('')
print('-'*12)
print('Para poder calcular a quantidade de tinta a ser usada... \nÉ necessário calcular a área da parede que vai ser pintada. \nPara isso, vai ser necessário saber as medidas de altura e largura: \n(Tenha noção de que: 2m² de área = 1l de tinta.)')
print('')
alt = (float(input('Informe a Altura da Parede: ')))
larg = (float(input('Informe a Largura da Parece: ')))
area = (alt*larg)
print('-'*12)
print('')
print(f'De acordo com as informações fornecidas, a área dessa parede é de {area:.2f}m².')
print(f'Para pintar essa parede, seriam necessários {area/2:.02f}l de tinta.')
print('')
print('-'*24)