print('====================================')
print(' |        TELA DE CADASTRO        | ')
print('====================================')
print('')
print('-------------------------------------')
print('Olá! Seja bem vindo a nossa empresa! \nVocê é o nosso novo funcionário, e para continuar, pedimos algumas informações pessoais suas:')
print('')
print('=----------------------------=')
name1 = input('Nome: ')
age1 = input('Idade: ')
gender1 = input('Sexo: (Masculino | Feminino | Outro)\n')
birthday1 = input('Data de Nascimento: (00/00/00)\n')
occupation1 = input('Ocupação: ')
print('=----------------------------=')
print('')
print('Parabéns Dr.', name1,'Você concluiu o cadastro em nossa empresa. \nLogo você será informado de sua estadia, e aonde irá morar a partir de agora.')
print('')
print('=----------------------------=')
print('')
print('=======================================================================')
print('                                   PERFIL                              ')
print('Nome:', name1,            '\tIdade:', age1)
print('Sexo:', gender1,          '\tData de Nascimento', birthday1)
print('Ocupação:', occupation1,  '\tNível: 01')
print('=======================================================================')
print('Nota: Você ainda precisa comparecer presencialmente no escritório. \nData ainda será informada. \nEsteja Atento.')  
print('=======================================================================')